version: '3.8'

services:
  web:
    build: /opt/odev1/ilkDeneme
    command: gunicorn --workers 5 --bind 0.0.0.0:5001 merhaba:app
    ports:
      -  5000:5001
  nginx:
    build: /opt/odev1/ilkDeneme/nginx
    command: sudo systemctl start nginx.service
    ports:
      - 81:80
    depends_on:
      - web
